apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
        prometheus.io/path: '/api/metrics'
    spec:
      containers:
        - name: backend
          image: taskmanager-backend:latest
          imagePullPolicy: IfNotPresent # For local k3s
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '5000'
            - name: DB_HOST
              value: 'postgres-service'
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: 'taskmanager'
            - name: DB_USER
              value: 'admin'
            - name: DB_PASSWORD
              value: 'password'
            - name: JWT_SECRET
              value: 'your-k8s-jwt-secret'
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: taskmanager
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
