# =============================================================================
# SECRETS MODULE
# Stores application secrets in AWS Secrets Manager.
#
# Concept: Secret Management — secrets never live in Git or environment files.
# The External Secrets Operator (installed in Sesja 2) will sync these into
# Kubernetes Secrets automatically, so pods can consume them as env vars.
# =============================================================================

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.50"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

# ─── DB PASSWORD ─────────────────────────────────────────────────────────────
# Generated by Terraform — never manually set, never stored in code

resource "random_password" "db_password" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "db_password" {
  name                    = "${var.project}/${var.environment}/db-password"
  description             = "PostgreSQL password for ${var.project} ${var.environment}"
  recovery_window_in_days = 0 # instant deletion (dev — avoids recovery window cost)

  tags = var.tags
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db_password.result
}

# ─── JWT SECRET ──────────────────────────────────────────────────────────────

resource "random_password" "jwt_secret" {
  length  = 64
  special = false # alphanumeric only — safe for JWT signing
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = "${var.project}/${var.environment}/jwt-secret"
  description             = "JWT signing secret for ${var.project} ${var.environment}"
  recovery_window_in_days = 0

  tags = var.tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = random_password.jwt_secret.result
}
